apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: apisimplona-api
  description: Descreve a API Simplona
spec:
  type: openapi
  lifecycle: production
  owner: marketplace
  system: apisimplona 
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Api Simplona API
    servers:
      - url: http://172.18.208.1:8080/mensagem
    paths:
      /simples:
        get:
          summary: exibe uma mensagem simples
      /elaborada:
          summary: exibe uma mensagem elaborada
